version: '3.3'

services:
  open_school_db:
    image: mysql:8.0.0
    restart: always
    environment:
      MYSQL_DATABASE: 'open_school_db'
      MYSQL_USER: 'open-school-user'
      MYSQL_PASSWORD: 'open-school-password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data/db:/var/lib/mysql

# useful commands
# docker-compose up -d
# docker-compose config