spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/open-school-db #?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: open-school-user
    password: open-school-password



