server:
  port: 5000

jwt:
  token-exp-time: 432_000_000 # 5 days
  secret: 'ksfhlksjlkesjl;jksl;kfldskdl;ksfl;ks65456s465f4ds68f4dsf46ds4f5snkldj+dlksfnklslsjdkfljsdk'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://awseb-e-ifh3vhuuyk-stack-awsebrdsdatabase-ihwfox4tu4ds.cbeyaci1cgqp.eu-central-1.rds.amazonaws.com:3306/open_school_db?allowPublicKeyRetrieval=true&useSSL=false
    username: dev_user
    password: Password1!

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  flyway:
    locations: "classpath:db/migration/{vendor}"
    clean-on-validation-error: true

  mail:
    username: openschool.epam@gmail.com
    password: ueiafqlkvmahqari
    port: 587
    host: smtp.gmail.com
    personal: Open school support
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    default-encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB

verification:
  duration: 3 # minutes
  cookie-expiration: 120 # seconds
  subject: 'Verify your account'
  endpoint: 'http://open-school-dev.eu-central-1.elasticbeanstalk.com/api/v1/auth/account/verification'
  reset:
    password:
      email:
        subject: Verification code to reset your password

token:
  expiration: 30

springdoc:
  swagger-ui:
    path: /open-school-api
    operationsSorter: method

cloud:
  aws:
    region:
      static: eu-central-1
    stack:
      auto: false

application:
  bucket:
    name: open-school-images

mail:
  username: openschool.epam@gmail.com





