server:
  port: 5000

jwt:
  token-exp-time: 432_000_000 # 5 days
  secret: 'ksfhlksjlkesjl;jksl;kfldskdl;ksfl;ks65456s465f4ds68f4dsf46ds4f5snkldj+dlksfnklslsjdkfljsdk'

verification:
  duration: 1 # 1day

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cbeyaci1cgqp.eu-central-1.rds.amazonaws.com:3306/open_school_db?useSSL=false
    username: dev_user
    password: Password1!

  flyway:
    locations: "classpath:db/migration/{vendor}"
    clean-on-validation-error: true

  mail:
    username: epam.open.school@gmail.com
    password: gaqbkpxlbmgjztwm
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    default-encoding: UTF-8

springdoc:
  swagger-ui:
    path: /open-school-api
    operationsSorter: method

logging:
  file:
    name: open-school-logs.log