spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/open_school_db?useSSL=false
    username: open-school-user
    password: open-school-password
  jpa:
    show-sql: true
  mail:
    username: epam.open.school@gmail.com
    password: gaqbkpxlbmgjztwm
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    default-encoding: UTF-8