jwt:
  token-exp-time: 432_000_000 # 5 days
  secret: 'ksfhlksjlkesjl;jksl;kfldskdl;ksfl;ks65456s465f4ds68f4dsf46ds4f5snkldj+dlksfnklslsjdkfljsdk'

spring:
  profiles:
    active: local
server:
  port: 5000


