name: Deploy to Dev
on:
  workflow_dispatch:
    inputs:
      artifact-version:
        description: 'Artifact version'
        required: true
        default: '45'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: keithweaver/aws-s3-github-action@v1.0.0 # Verifies the recursive flag
        name: Download ${{ INPUT_artifact-version }}
        with:
          command: cp
          source: s3://${{ secrets.AWS_S3_BUCKET_NAME }}/artifacts/os-server-${{artifact-version}}.jar
          destination: ./data/
          aws_access_key_id: ${{ secrets.AWS_S3_ACCESS_ID}}
          aws_secret_access_key: ${{ secrets.AWS_S3_ACCESS_KEY}}
          aws_region: eu-central-1

      - name: Deploy to EB dev environment
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_BT_SECRET_ID }}
          aws_secret_key: ${{ secrets.AWS_BT_SECRET_KEY }}
          application_name: open-school-dev
          environment_name: Openschooldev-env
          version_label: ${{ INPUT_artifact-version }}
          deployment_package: ./data/os-server-${{artifact-version}}.jar
          region: eu-central-1
