name: Open School pull request CI
on:

  pull_request:
    branches: [main]
jobs:
  bulid:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Check google java format into main/java package
#        run: ./gradlew checkstyleMain
#      - name: Check google java format into test/java package
#        run: ./gradlew checkstyleTest
#      - name: Build with Gradle
#        run: SPRING_PROFILES_ACTIVE=test ./gradlew build
#      - name: pwd
#        run: pwd
#      - name: ls
#        run: ls
#      - name: cd to os-ui
#        run: cd
#      - name: pwd
#        run: pwd
#      - name: ls
#        run: ls
      - name: Test and coverage
        run: npm test
#      - name: cd to open-school
#        run: cd \home\runner\work\open-school\open-school
      - name: sonar analyzes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube --info
      - name: Print Message
        run: echo "CI pipeline part finished successfully!"