name: Open School pull request CI
on:

  pull_request:
    branches: [main]
jobs:
  bulid:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check google java format into main/java package
        run: ./gradlew checkstyleMain
      - name: Check google java format into test/java package
        run: ./gradlew checkstyleTest
      - name: Build with Gradle
        run: SPRING_PROFILES_ACTIVE=test ./gradlew build
      - name: Print Message
        run: echo "CI pipeline part finished successfully!"