name: CI-upload-artifact

on:
  pull_request:
     types:
      - closed
jobs:
   if_merged:
       if: github.event.pull_request.merged == true

       runs-on: ubuntu-latest
       steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-java@v2
            with:
               java-version: '11'
               distribution: 'adopt'
          - name: Run gradle
            run: chmod +x gradlew
          - name: Build with Gradle
            uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
            with:
              arguments: build
          - name: sonar analyzes
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            run: ./gradlew sonarqube --info
          - name: Store artifact in github
            uses: actions/upload-artifact@v2
            with:
              name: os-server-${{ github.run_number }}.jar
              path: os-server/build/libs/os-server-**.jar
          - name: Rename file
            run: mv os-server/build/libs/os-server-**.jar os-server/build/libs/os-server-${{ github.run_number }}.jar
          - name: Upload to S3 as artifact
            uses: medlypharmacy/s3-artifacts-action@master
            with:
              aws_access_key_id: ${{ secrets.AWS_S3_ACCESS_ID}}
              aws_secret_access_key: ${{ secrets.AWS_S3_ACCESS_KEY}}
              aws_s3_bucket_name: ${{ secrets.AWS_S3_BUCKET_NAME }}
              source_path: 'os-server/build/libs/os-server-${{ github.run_number }}.jar'
              exclude_repo_from_destination_path: true
              destination_path: 'artifacts/os-server-${{ github.run_number }}.jar'
